@startuml Geometry Dash Hierarchy
' <|-- Extension
' *-- Composition
' o-- Aggregation
' <|.. dotted line

' Dion's section, gamemodes  
interface IInput {
    void OnTap()
    void OnHold()
}

class CubeState {
    void Execute()
}
class ShipState {
    void Execute()
}
class BallState {
    void Execute()
}
class UFOState {
    void Execute()
}
class WaveState {
    void Execute()
}
class RobotState {
    void Execute()
}
class SpiderState {
    void Execute()
}

class StateMachine {
    enum GamemodeTypes
    Dictionary[] states
    void ChangeState
}

' Connections 
CubeState <|.. IInput
ShipState <|.. IInput
BallState <|.. IInput
UFOState <|.. IInput
WaveState <|.. IInput
RobotState <|.. IInput
SpiderState <|.. IInput

CubeState <-> StateMachine
ShipState <-> StateMachine
BallState <-> StateMachine
UFOState <-> StateMachine
WaveState <-> StateMachine
RobotState <-> StateMachine
SpiderState <-> StateMachine

@enduml 